1.	Write a Python program to select an item randomly from a list.
2.	Write a Python program to count the elements in a list until an element is a tuple
3.	Create a dictionary of 5 countries with their currency details and display them.
4.	Write a Python program to reverse a tuple.
5.	Create a Numpy array filled with all ones
6.	Check whether a Numpy array contains a specified row
7.	Compute mathematical operations on Array, Add & Multiply two matrices
8.	Find the most frequent value in a NumPy array
9.	Flatten a 2d numpy array into ld array
10.	Calculate the sum of all columns in a 2D NumPy array
11.	Calculate the average, variance and standard deviation in Python using NumPy
12.	Insert a space between characters of all the elements of a given NumPy array?
13.	Sort the values in a matrix

### ANISH SHARMA
### I011
### 60003220045

In [10]:
lst = [1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [11]:
import random as r

In [14]:
r.choice(lst)

5

In [15]:
dict={
    "India":"Rupees",
    "USA":"Dollar",
    "Afghanistan":"Afghani",
    "Andorra":"Euro",
    "Albania":"Dinar"
}
dict

{'India': 'Rupees',
 'USA': 'Dollar',
 'Afghanistan': 'Afghani',
 'Andorra': 'Euro',
 'Albania': 'Dinar'}

In [16]:
t = (1,2,3,4,5)
t[::-1]

(5, 4, 3, 2, 1)

In [17]:
import numpy as np

In [20]:
arr = np.ones(5,int)

In [21]:
arr

array([1, 1, 1, 1, 1])

In [28]:
m1 = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
m2= np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [29]:
m1+m2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [30]:
m1*m2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [32]:
m1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
m1.sum()

45

In [43]:
arr = np.array([1,2,3,4,5],int)
np.average(arr)

3.0

In [45]:
np.std(arr)

1.4142135623730951

In [46]:
np.var(arr)

2.0

In [48]:
x = np.array(["geeks", "for", "geeks"])

In [49]:
r = np.char.join(" ", x)
r

array(['g e e k s', 'f o r', 'g e e k s'], dtype='<U9')

In [53]:
np.sort(m2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr = np.array([[1, 2, 3, 4, 5], 
                   [6, 7, 8, 9, 10], 
                   [11, 12, 13, 14, 15], 
                   [16, 17, 18, 19, 20] 
                   ]) 

In [56]:
print([1, 2, 3, 4, 5] in arr.tolist()) 

True


In [57]:
print([1, 2,5 , 3, 4, 5] in arr.tolist()) 

False


In [58]:
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
print(np.bincount(x).argmax())

1


In [61]:
a = [[1,2,3],[4,5,6],tuple(7,8,9)]

TypeError: tuple expected at most 1 argument, got 3

In [60]:
for i in a:
    if a is not tuple:
        print(i)

[1, 2, 3]
[4, 5, 6]
(7, 8, 9)


In [63]:
def Count(li):
   
    for num in li:
        if isinstance(num, tuple):
            break
       
        print(num)
 
li = [4, 5, 6, 10, (1, 2, 3), 11, 2, 4]


4
5
6
10
4
